[default]
bootstrap.servers = broker:9092
# 'auto.offset.reset=earliest' to start reading from the beginning of
# the topic if no committed offsets exist.
auto.offset.reset=earliest

[monitor]
group.id=monitor

[connection]
group.id=connection

[channel_encryption]
group.id=channel_encryption

[integration]
group.id=integration

[navigation_gnss]
group.id=navigation_gnss

[navigation_ins]
group.id=navigation_ins

[route_planner]
group.id=route_planner

[task_orchestrator]
group.id=task_orchestrator

[camers]
group.id=camers

[lidar]
group.id=lidar

[ir_sensors]
group.id=ir_sensors

[cargo_monitoring_system]
group.id=cargo_monitoring_system

[data_processing]
group.id=data_processing

[decision_making]
group.id=decision_making

[motion_control]
group.id=motion_control

[taxiing]
group.id=taxiing

[taxiing_system]
group.id=taxiing_system

[acceleration_and_deceleration]
group.id=acceleration_and_deceleration

[engin_management]
group.id=engin_management

[alarm_systems]
group.id=alarm_systems

[self_diagnostic]
group.id=self_diagnostic

[emergency_unit]
group.id=emergency_unit

[emergency_speed_reduction]
group.id=emergency_speed_reduction

[emulated]
group.id=emulated
